name: Setup FEServer

on:
  push:
    branches: [ "main" ]
    
jobs:
  setup-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.AWS_SSH_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}


      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y ssh

      - name: Copy Nginx Configuration
        run: scp -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no -r ./nginx-config/ ${{ secrets.AWS_SSH_USER }}@${{ secrets.SERVER_HOST }}:~/nginx-config
     
          
      - name: Run Setup Script on Remote Server
        run: ssh -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.AWS_SSH_USER }}@${{ secrets.SERVER_HOST }} 'bash -s' < ./nginx-config/setup.sh
