name: Setup FEServer

on:
  push:
    branches: [ "main" ]
    
jobs:
  setup-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 서버 설정
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.AWS_SSH_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: 
            # nginx 설정 파일 업로드
            echo "server {
                     listen 80;
                     server_name  ${{ secrets.SERVER_HOST }};
                 
                     location / {
                         root C:\myWorkplace\dwanGim_FE;
                         index index.html;
                     }
                 
                     location /api/ {
                         proxy_pass http://localhost:3001;
                         proxy_set_header Host $host;
                         proxy_set_header X-Real-IP $remote_addr;
                         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                         proxy_set_header X-Forwarded-Proto $scheme;
                     }
                 }" > /etc/nginx/sites-available/my-site
            sudo cp ~/my-site /etc/nginx/sites-available/my-site
            sudo ln -s /etc/nginx/sites-available/my-site /etc/nginx/sites-enabled/my-site
            sudo nginx -t
            sudo service nginx restart

