name: Setup and Deploy Server

on:
  push:
    branches: [ "main" ]

jobs:
  setup-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug GitHub Actions Environment
        run: |
          echo "HOME: ~/"
          ls -la ~/


      - name: Setup Server
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > $HOME/.ssh/config
          sudo apt-get update
          sudo apt-get install -y ssh



  deploy:
    needs: setup-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Setup Script on Remote Server
        run: |
          scp -i ~/.ssh/id_rsa ./nginx-config/setup.sh ${{ secrets.AWS_SSH_USER }}@${{ secrets.SERVER_HOST }}:~/nginx-config/
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.AWS_SSH_USER }}@${{ secrets.SERVER_HOST }} 'bash -s' < ~/nginx-config/setup.sh

      - name: Copy Nginx Configuration
        run: scp -i ~/.ssh/id_rsa -r ./nginx-config/ ${{ secrets.AWS_SSH_USER }}@${{ secrets.SERVER_HOST }}:~/nginx-config
      

